name: hackaton_module
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - geopandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - lightgbm
  - pyyaml
